packageExtensions:
  "@firebase/database@*":
    dependencies:
      "@firebase/app": "*"
  esbuild-loader@*:
    dependencies:
      webpack: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  react-ga@*:
    dependencies:
      prop-types: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-monorail.cjs
    spec: packages/yarn-plugin-monorail/bundles/@yarnpkg/plugin-monorail.js

yarnPath: .yarn/releases/yarn-2.4.1.cjs
