packageExtensions:
  "@docusaurus/core@*":
    dependencies:
      lodash.flatmap: "*"
  "@docusaurus/plugin-content-docs@*":
    dependencies:
      chalk: "*"
      lodash: "*"
  "@docusaurus/theme-search-algolia@*":
    dependencies:
      "@docusaurus/utils": ^2.0.0-alpha.56
  next@*:
    dependencies:
      "@types/react": "*"
      caniuse-lite: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  prism-react-renderer@*:
    dependencies:
      "@types/react": "*"
  react-ga@*:
    dependencies:
      prop-types: "*"
  react-loadable-ssr-addon@*:
    dependencies:
      "@babel/runtime": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-generate-workspaces-json.cjs
    spec: "https://raw.githubusercontent.com/SamChou19815/yarn-plugins/master/.yarn/plugins/%40yarnpkg/plugin-generate-workspaces-json.cjs"

yarnPath: .yarn/releases/yarn-2.2.0.cjs
