packageExtensions:
  "@firebase/database@*":
    dependencies:
      "@firebase/app": "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  react-ga@*:
    dependencies:
      prop-types: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-generate-workspaces-json.cjs
    spec: packages/yarn-plugin-generate-workspaces-json/bundles/@yarnpkg/plugin-generate-workspaces-json.js

yarnPath: .yarn/releases/yarn-2.4.0.cjs
