packageExtensions:
  '@aldridged/docusaurus-plugin-lunr@*':
    dependencies:
      classnames: '*'
      core-js: '2'
      react-router-dom: '*'
      regenerator-runtime: '*'
  '@docusaurus/plugin-sitemap@*':
    dependencies:
      fs-extra: '2'
  '@docusaurus/theme-classic@*':
    dependencies:
      core-js: '2'
  '@docusaurus/theme-search-algolia@*':
    dependencies:
      '@docusaurus/utils': '^2.0.0-alpha.56'
      core-js: '2'
  '@firebase/firestore@*':
    dependencies:
      protobufjs: '*'
  '@google-cloud/pubsub@*':
    dependencies:
      '@grpc/grpc-js': '*'
  'blog@*':
    dependencies:
      core-js: '2'
  'firebase-tools@*':
    dependencies:
      winston-transport: '*'
  'lib-docusaurus-plugin@*':
    dependencies:
      core-js: '2'
  'lib-react@*':
    dependencies:
      core-js: '2'
  'next@*':
    dependencies:
      '@types/react': '*'
  'prism-react-renderer@*':
    dependencies:
      '@types/react': '*'
  'react-loadable-ssr-addon@*':
    dependencies:
      '@babel/runtime': '*'
  'samlang@*':
    dependencies:
      core-js: '2'
  'wiki@*':
    dependencies:
      core-js: '2'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.1.1.cjs
