packageExtensions:
  "@docusaurus/core@*":
    dependencies:
      "@babel/runtime": 7.10.4
      "@babel/runtime-corejs3": 7.10.4
  "@firebase/database@*":
    dependencies:
      "@firebase/app": "*"
  "@grpc/grpc-js@*":
    dependencies:
      google-auth-library: "*"
  next@*:
    dependencies:
      caniuse-lite: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  react-ga@*:
    dependencies:
      prop-types: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-generate-workspaces-json.cjs
    spec: "https://raw.githubusercontent.com/SamChou19815/yarn-plugins/master/.yarn/plugins/%40yarnpkg/plugin-generate-workspaces-json.cjs"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
