packageExtensions:
  '@docusaurus/core@*':
    dependencies:
      lodash.flatmap: '*'
  '@docusaurus/plugin-content-docs@*':
    dependencies:
      chalk: '*'
      lodash: '*'
  '@docusaurus/theme-search-algolia@*':
    dependencies:
      '@docusaurus/utils': '^2.0.0-alpha.56'
  'next@*':
    dependencies:
      '@types/react': '*'
      'caniuse-lite': '*'
  'prism-react-renderer@*':
    dependencies:
      '@types/react': '*'
  'react-ga@*':
    dependencies:
      'prop-types': '*'
  'react-loadable-ssr-addon@*':
    dependencies:
      '@babel/runtime': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.1.1.cjs
