version: 2.1
jobs:
  code-quality-check:
    description: Run code quality checks
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-dependencies-{{ .Branch }}-
            - yarn-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Check sam-highlighter
      - run: cd sam-highlighter && yarn tsc
      # Check main-site-frontend
      - run: cd main-site-frontend && yarn tsc
      - run: cd main-site-frontend && yarn lint
      # Check samlang-demo-frontend:
      - run: cd samlang-demo-frontend && yarn tsc
      - run: cd samlang-demo-frontend && yarn lint
      # Check ten-web-frontend:
      - run: cd ten-web-frontend && yarn tsc
      - run: cd ten-web-frontend && yarn lint
  deploy-changed-frontend:
    description: Deploy changed frontend directory to firebase hosting
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy to Firebase
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              ./ci-deploy
            else
              echo "Not master branch, do not deploy"
            fi
workflows:
  version: 2
  check-and-deploy-frontend:
    jobs:
      - code-quality-check
      - deploy-changed-frontend:
          requires:
            - code-quality-check
