//! Blog posts, generated by build.rs from packages/www. See [`EncryptedRun`].

use crate::crypt::{EncryptedRun, EncryptedString};
use crate::site_path::SitePath;

/// Variant names must match what build.rs emits.
#[derive(Clone, Copy)]
pub(crate) enum SpanColor {
    Keyword,
    String,
    Number,
    Function,
    Type,
    Comment,
}

/// Byte range within one line.
pub(crate) struct CodeSpan {
    pub(crate) start: u32,
    pub(crate) len: u32,
    pub(crate) color: SpanColor,
}

pub(crate) struct CodeBlock {
    pub(crate) lines: &'static [&'static [CodeSpan]],
}

pub(crate) struct Post {
    title: EncryptedRun,
    year: EncryptedRun,
    month: EncryptedRun,
    date: EncryptedRun,
    /// Empty for external posts.
    slug: EncryptedRun,
    external_url: Option<EncryptedRun>,
    /// Markdown with frontmatter stripped. Empty for external posts.
    body: EncryptedRun,
    /// One per fenced block, in order. Empty lines for samlang (highlighted at runtime) and
    /// unknown languages.
    code_blocks: &'static [CodeBlock],
}

include!(concat!(env!("OUT_DIR"), "/posts.rs"));

pub(crate) fn blog_title() -> EncryptedString {
    BLOG_TITLE.of(POSTS_BLOB)
}

impl Post {
    pub(crate) fn title(&self) -> EncryptedString {
        self.title.of(POSTS_BLOB)
    }

    pub(crate) fn body(&self) -> EncryptedString {
        self.body.of(POSTS_BLOB)
    }

    pub(crate) fn code_blocks(&self) -> &'static [CodeBlock] {
        self.code_blocks
    }

    pub(crate) fn is_external(&self) -> bool {
        self.external_url.is_some()
    }

    pub(crate) fn formatted_date(&self) -> String {
        format!(
            "{}-{}-{}",
            self.year.of(POSTS_BLOB),
            self.month.of(POSTS_BLOB),
            self.date.of(POSTS_BLOB)
        )
    }

    /// Only meaningful for local posts.
    pub(crate) fn path(&self) -> SitePath {
        SitePath::new(format!(
            "/blog/{}/{}/{}/{}",
            self.year.of(POSTS_BLOB),
            self.month.of(POSTS_BLOB),
            self.date.of(POSTS_BLOB),
            self.slug.of(POSTS_BLOB)
        ))
    }

    pub(crate) fn url(&self) -> String {
        match self.external_url {
            Some(url) => url.of(POSTS_BLOB).decrypt(),
            None => format!("https://developersam.com{}", self.path()),
        }
    }
}

pub(crate) fn find(path: &SitePath) -> Option<usize> {
    POSTS
        .iter()
        .position(|post| !post.is_external() && &post.path() == path)
}
