/**
 * The Rust/iocraft backend (`crates/sam-tui`), and the browser's half of the
 * bargain with it.
 *
 * The backend is a real terminal application: it writes ANSI (alternate screen,
 * mouse capture, synchronized updates) to an in-memory stream and parses raw
 * input bytes. It also decides everything it has the data to decide — the shell
 * prompt, the blog's titles, where a link leads. What it cannot do is reach the
 * browser, so it asks, one line at a time, through `pollEvent`.
 *
 * The bridge itself is generated by wasm-bindgen (`pnpm build:wasm`) into
 * `../generated/`; this module fetches the binary and applies what comes back.
 */

import init, * as wasm from "../generated/sam_tui";

export type Backend = Omit<typeof wasm, "default" | "initSync">;

export async function loadBackend(): Promise<Backend> {
  await init();
  return wasm;
}

/** The path in the URL bar, with any trailing slash trimmed off. */
export function currentPath(): string {
  const path = window.location.pathname;
  return path.length > 1 ? path.replace(/\/+$/, "") : path;
}

/**
 * Acts on one line from `pollEvent`: `open <url>`, or
 * `route push|replace <path>\t<title>`. These are the things the backend cannot
 * do for itself, and nothing it can.
 *
 * `router.replace` is a no-op under `output: "export"` (see the same note in
 * budget/Tabs.tsx), and the History API is what a terminal wants anyway: no
 * navigation, no reload, just the address kept honest.
 */
export function applyHostEvent(event: string): void {
  const [head, title] = event.split("\t");
  const [kind, ...rest] = (head ?? "").split(" ");
  if (kind === "open") {
    // Only http(s) leaves: the page renders whatever bytes reach it, and a
    // `javascript:` URL would run in this document. The backend refuses those
    // too — this is the guard at the one place that actually navigates.
    const url = rest.join(" ");
    if (/^https?:\/\//i.test(url)) {
      window.open(url, "_blank", "noopener");
    }
    return;
  }
  if (kind !== "route") {
    return;
  }
  const [mode, path] = rest;
  if (path == null) {
    return;
  }
  if (path !== currentPath()) {
    window.history[mode === "replace" ? "replaceState" : "pushState"](null, "", path);
  }
  document.title = title ?? "";
}
