//! Bakes the homepage's card artwork into the binary as small RGB pixel grids.
//!
//! The TUI paints images as half-blocks (`▀`), so one cell carries two stacked
//! pixels and the pixel grid is roughly square. Each asset is fitted into
//! [`MAX_COLS`]x[`MAX_ROWS`] cells — the largest any placement asks for — and
//! resampled once, here, at build time. The runtime box-filters that grid down
//! for smaller placements, so a single bake serves both the card thumbnails and
//! the modal hero.
//!
//! Baking pixels rather than finished `(fg, bg)` cell pairs costs the same six
//! bytes per cell and stays resamplable. The whole set is ~63KB.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// The largest cell box any placement uses (the detail modal's hero).
const MAX_COLS: u32 = 56;
const MAX_ROWS: u32 = 16;

/// Site-root-relative asset paths, which double as the `<img src>` the web
/// overlay needs and as the key `data.rs` refers to them by.
const ASSETS: &[&str] = &[
    "/timeline/courseplan-promotion.png",
    "/timeline/critter-compiler.webp",
    "/timeline/critter-world.webp",
    "/timeline/fb-sticker-pen.webp",
    "/timeline/flow.webp",
    "/timeline/pyre-check.webp",
    "/timeline/sam-later.webp",
    "/timeline/sampl.webp",
    "/timeline/website-v2.webp",
    "/timeline/website-v3.webp",
    "/projects/mini-react.webp",
    "/projects/samlang.webp",
    "/projects/samwise.webp",
    "/projects/ten.webp",
    "/fan-arts/graduation-sam.webp",
    "/sam-by-megan-3-square.webp",
];

/// Cells an image of `width`x`height` occupies when fitted into the box,
/// preserving aspect. Two pixels per cell vertically is what makes the
/// comparison against a 1:1 pixel grid correct.
fn fit(width: u32, height: u32) -> (u32, u32) {
    let mut cols = MAX_COLS;
    let mut rows = ((cols as f64 * height as f64) / (2.0 * width as f64)).round() as u32;
    if rows > MAX_ROWS {
        rows = MAX_ROWS;
        cols = ((2.0 * rows as f64 * width as f64) / height as f64).round() as u32;
    }
    (cols.clamp(1, MAX_COLS), rows.max(1))
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let public = manifest.join("../../packages/www/public");
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed=build.rs");

    let mut blob: Vec<u8> = Vec::new();
    let mut index = String::new();

    for url in ASSETS {
        let source: &Path = &public.join(url.trim_start_matches('/'));
        println!("cargo:rerun-if-changed={}", source.display());

        let decoded = image::ImageReader::open(source)
            .unwrap_or_else(|error| panic!("opening {}: {error}", source.display()))
            .decode()
            .unwrap_or_else(|error| panic!("decoding {}: {error}", source.display()))
            .to_rgb8();
        let (cols, rows) = fit(decoded.width(), decoded.height());
        let resized = image::imageops::resize(
            &decoded,
            cols,
            rows * 2,
            image::imageops::FilterType::Lanczos3,
        );

        let offset = blob.len();
        blob.extend_from_slice(resized.as_raw());
        writeln!(
            index,
            "    Baked {{ url: {url:?}, cols: {cols}, rows: {rows}, offset: {offset}, len: {} }},",
            blob.len() - offset,
        )
        .expect("writing to a String cannot fail");
    }

    std::fs::write(out.join("images.bin"), &blob).expect("writing images.bin");
    std::fs::write(
        out.join("images.rs"),
        format!(
            "// @generated by build.rs — do not edit.\n\
             static BLOB: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/images.bin\"));\n\
             static INDEX: &[Baked] = &[\n{index}];\n"
        ),
    )
    .expect("writing images.rs");
}
