/**
 * Loader for the Rust/iocraft backend (`crates/sam-tui`).
 *
 * The backend is a real terminal application: it writes ANSI (alternate
 * screen, mouse capture, synchronized updates) to an in-memory stream and
 * parses raw input bytes. JS relays bytes between it and xterm.js — no frame
 * protocol, no key mapping.
 *
 * The bridge itself is generated by wasm-bindgen (`pnpm build:wasm`) into
 * `./generated/`; this module only fetches the binary and re-exports it.
 */

import init, * as wasm from "./generated/sam_tui";

export type SamTui = Omit<typeof wasm, "default" | "initSync">;

export async function loadSamTui(): Promise<SamTui> {
  await init();
  return wasm;
}
