name: CD
on:
  push:
    branches:
      - main
env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        with:
          path: '.yarn/cache'
          key: "yarn-berry-${{ hashFiles('**/yarn.lock') }}"
          restore-keys: 'yarn-berry-'
      - name: Yarn Install
        run: yarn install --immutable
      - name: Build and Deploy
        run: scripts/deploy.js
