# @generated

name: ci-main-site-frontend
on:
  pull_request:
    paths:
      - .github/workflows/ci-workflow-main-site-frontend.yml
      - configuration/*
      - tooling/*
      - sam-highlighter/*
      - main-site-frontend/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install

      - name: Build dependency: sam-highlighter
        run: yarn workspace build sam-highlighter
      - name: Build main-site-frontend
        run: yarn workspace build main-site-frontend
