name: General
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Format Check
        run: pnpm format:check
      - name: Lint
        run: pnpm lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Type Check
        run: pnpm compile -- --since="HEAD^"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm test
