name: General
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "2"
      - uses: oven-sh/setup-bun@v1
      - name: Bun Install
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint
      - name: Type Check
        run: bun run check
      - name: Build
        run: bun run build
