name: CI-CD
on:
  push:
    branches:
      - master

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: CI Deploy
        env:
          DEPLOY_GH_PAGE_TOKEN: ${{ secrets.DEPLOY_GH_PAGE_TOKEN }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: ./ci-deploy
