name: CI-CD
on: [pull_request]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install
      # sam-highlighter
      - name: Type Check and Build sam-highlighter
        run: yarn workspace sam-highlighter build
      # main-site-frontend
      - name: Type Check main-site-frontend
        run: yarn workspace main-site-frontend tsc
      - name: Lint main-site-frontend
        run: yarn workspace main-site-frontend lint
      # samlang-demo-frontend
      - name: Type Check samlang-demo-frontend
        run: yarn workspace samlang-demo-frontend tsc
      - name: Lint samlang-demo-frontend
        run: yarn workspace samlang-demo-frontend lint
      # ten-web-frontend
      - name: Type Check ten-web-frontend
        run: yarn workspace ten-web-frontend tsc
      - name: Lint ten-web-frontend
        run: yarn workspace ten-web-frontend lint
      # blog
      - name: Build blog
        run: yarn workspace blog build
