name: Dummy
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "Lint nothing."
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "Build nothing."
