name: dummy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Do Nothing
        run: echo "Bye!"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Do Nothing
        run: echo "Bye!"
