# @generated

name: cd-blog
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/generated-cd-blog.yml
      - package.json
      - 'configuration/**'
      - 'sam-react-common/**'
      - 'blog/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install

      - name: Build blog
        run: yarn workspace blog build

      - name: Install Firebase Tools
        run: yarn add --dev firebase-tools -W
      - name: Deploy blog
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          ./node_modules/.bin/firebase deploy \
          --token=$FIREBASE_TOKEN --non-interactive --only hosting:blog

      - name: Create Success Status
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.DEPLOY_GH_PAGE_TOKEN }}
          script: |
            github.repos.createStatus({
              owner: 'SamChou19815',
              repo: 'website',
              sha: '${{github.sha}}',
              state: 'success',
              context: 'github-actions: cd-blog',
              description: 'Passed CI Tests!',
            });

