# @generated

name: lint-generated
on:
  push:
    paths:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - name: Codegen
        run: packages/monorail/bin/index.js codegen
      - name: Check changed
        run: if [[ `git status --porcelain` ]]; then exit 1; fi
