# @generated

name: CI samlang
on:
  push:
    paths:
      - packages/lib-react/**
      - packages/samlang/**
      - package.json
      - yarn.lock
      - configuration/**
      - .github/workflows/generated-*-samlang.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install
      - name: Compile
        run: yarn workspace samlang compile
      - name: Test
        run: yarn workspace samlang test
