# @generated

name: CD
on:
  push:
    branches:
      - master
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Install
        run: python -m builder.builder install-for-deploy-if-affected

      - name: Deploy blog
        if: always()
        run: python -m builder.builder deploy-if-affected --workspace blog

      - name: Deploy main-site-frontend
        if: always()
        run: python -m builder.builder deploy-if-affected --workspace main-site-frontend

      - name: Deploy samlang-demo-frontend
        if: always()
        run: python -m builder.builder deploy-if-affected --workspace samlang-demo-frontend

      - name: Deploy samlang-docs
        if: always()
        run: python -m builder.builder deploy-if-affected --workspace samlang-docs

      - name: Deploy ten-web-frontend
        if: always()
        run: python -m builder.builder deploy-if-affected --workspace ten-web-frontend

