# @generated

name: CI @dev-sam/eslint-config-common
on:
  push:
    paths:
      - 'packages/eslint-config-common/**'
      - 'package.json'
      - 'yarn.lock'
      - 'configuration/**'
      - '.github/workflows/generated-*-@dev-sam/eslint-config-common.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            .pnp.js
          key: yarn-berry-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-berry-
      - name: Yarn Install
        run: yarn install
      - name: Compile
        run: yarn workspace @dev-sam/eslint-config-common compile
