# @generated

name: General
on:
  push:
    paths:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            .pnp.js
          key: yarn-berry-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-berry-
      - name: Yarn Install
        run: yarn install --immutable
      - name: Codegen
        run: yarn node packages/monorail/bin/index.js codegen
      - name: Check changed
        run: if [[ `git status --porcelain` ]]; then exit 1; fi
      - name: Format Check
        run: yarn format:check
      - name: Lint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2-beta
      - uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            .pnp.js
          key: yarn-berry-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-berry-
      - name: Yarn Install
        run: yarn install --immutable
      - name: Build
        run: yarn compile
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            .pnp.js
          key: yarn-berry-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-berry-
      - name: Yarn Install
        run: yarn install --immutable
      - name: Test
        run: yarn test
