# @generated

name: lint-generated
on:
  push:
    paths:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Codegen
        run: yarn codegen
      - name: Check changed
        run: git status --porcelain
