# @generated

name: CI tasks
on:
  push:
    paths:
      - packages/lib-common/**
      - packages/lib-firebase/**
      - packages/lib-react/**
      - packages/tasks/**
      - package.json
      - yarn.lock
      - configuration/**
      - .github/workflows/generated-*-tasks.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install
      - name: Compile
        run: yarn workspace tasks compile
      - name: Test
        run: yarn workspace tasks test
