# @generated

name: lint-markdown
on:
  push:
    paths:
      - '.github/workflows/generated-lint-markdown.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Setup Markdown Lint
        run: gem install mdl
      - name: Run Markdown Lint
        run: mdl .
