# @generated

name: lint-generated
on:
  push:
    paths:
      - '**'

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - name: Codegen
        run: ./packages/monorail/bin/monorail codegen
      - name: Check changed
        run: git diff --quiet --exit-code
