# @generated

name: CI samlang
on:
  pull_request:
    paths:
      - packages/lib-react/**
      - packages/samlang/**
      - package.json
      - yarn.lock
      - configuration/**
      - .github/workflows/generated-*-samlang.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Use Yarn Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Yarn Install
        run: yarn install
      - name: Compile
        run: yarn workspace samlang compile
      - name: Test
        run: yarn workspace samlang test
