# @generated

name: CD ten
on:
  push:
    paths:
      - 'packages/lib-react-loading/**'
      - 'packages/lib-firebase/**'
      - 'packages/esbuild-scripts/**'
      - 'packages/ten/**'
      - 'configuration/**'
      - '.github/workflows/generated-*-ten.yml'
    branches:
      - main
env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
      - name: Yarn Install
        run: yarn install --immutable
      - name: Build
        run: yarn workspace ten build
      - name: Deploy
        run: yarn workspace ten deploy
