# @generated

name: ci-blog
on:
  pull_request:
    paths:
      - .github/workflows/generated-ci-blog.yml
      - package.json
      - 'configuration/**'
      - 'sam-react-common/**'
      - 'blog/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install

      - name: Build blog
        run: yarn workspace blog build
