# @generated

name: ci-samlang-demo-frontend
on:
  pull_request:
    paths:
      - .github/workflows/generated-ci-samlang-demo-frontend.yml
      - package.json
      - 'configuration/**'
      - 'sam-react-common/*'
      - 'samlang-demo-frontend/*'
      - 'samlang-demo-frontend/*/*'
      - 'samlang-demo-frontend/*/*/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install

      - name: Build samlang-demo-frontend
        run: yarn workspace samlang-demo-frontend build

      - name: Upload Built Static Assets
        uses: actions/upload-artifact@master
        with:
          name: built-samlang-demo-frontend-assets
          path: samlang-demo-frontend/build

      - name: Create Success Status
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.DEPLOY_GH_PAGE_TOKEN }}
          script: |
            github.repos.createStatus({
              owner: 'SamChou19815',
              repo: 'website',
              sha: '${{github.sha}}',
              state: 'success',
              context: 'github-actions: ci-samlang-demo-frontend',
              description: 'Passed CI Tests!',
            });

