# @generated

name: ci-main-site-frontend
on:
  pull_request:
    paths:
      - .github/workflows/generated-ci-main-site-frontend.yml
      - package.json
      - 'configuration/**'
      - 'sam-react-common/*'
      - 'main-site-frontend/*'
      - 'main-site-frontend/*/*'
      - 'main-site-frontend/*/*/*'
      - 'main-site-frontend/*/*/*/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install

      - name: Build main-site-frontend
        run: yarn workspace main-site-frontend build
      - name: Install react-snap
        run: yarn add react-snap --dev -W
      - name: Run react-snap
        run: yarn workspace main-site-frontend ci-postbuild

      - name: Upload Built Static Assets
        uses: actions/upload-artifact@master
        with:
          name: built-main-site-frontend-assets
          path: main-site-frontend/build

      - name: Create Success Status
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.DEPLOY_GH_PAGE_TOKEN }}
          script: |
            github.repos.createStatus({
              owner: 'SamChou19815',
              repo: 'website',
              sha: '${{github.sha}}',
              state: 'success',
              context: 'github-actions: ci-main-site-frontend',
              description: 'Passed CI Tests!',
            });

