# @generated

name: TS and JS
on:
  push:
    paths:
      - '.github/workflows/generated-ts-js.yml'
      - 'package.json'
      - '**/package.json'
      - '**.js'
      - '**.ts'
      - '**.jsx'
      - '**.tsx'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            .pnp.js
          key: yarn-berry-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-berry-
      - name: Yarn Install
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          depth: 2
      - uses: actions/setup-node@v2-beta
      - uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            .pnp.js
          key: yarn-berry-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-berry-
      - name: Yarn Install
        run: yarn install --immutable
      - name: Build
        run: yarn compile
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            .pnp.js
          key: yarn-berry-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-berry-
      - name: Yarn Install
        run: yarn install --immutable
      - name: Test
        run: yarn test
