name: lint-workflows
on:
  pull_request:
    paths:
      - .github/workflows/
      - package.json
      - configuration/**
      - tooling/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install
      - name: Validate Dependencies
        run: yarn validate-dependency
      - name: Generate Workflows
        run: yarn generate-workflows --out .github/workflows
      - name: Check changed
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Workflow files are not in sync!"
            exit 1
          else
            echo "Workflow files are in sync. Good to go!"
          fi
