name: lint-markdown
on:
  push:
    paths:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
      - name: Setup Markdown Lint
        run: gem install mdl
      - name: Run Markdown Lint
        run: mdl .
