name: lint-workflows
on: pull_request

jobs:
  lint-generated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Validate Dependencies
        run: python -m builder.builder validate-dependencies
      - name: Generate Workflows
        run: python -m builder.builder generate-workflows
      - name: Check changed
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Workflow files are not in sync!"
            exit 1
          else
            echo "Workflow files are in sync. Good to go!"
          fi
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
      - name: Setup Markdown Lint
        run: gem install mdl
      - name: Run Markdown Lint
        run: mdl .
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install linters
        run: python3 -m pip install -U black flake8
      - name: Lint with black
        run: black --check .
      - name: Lint with flake8
        run: flake8 .
  lint-yarn-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install
      - name: Upload Install Cache
        uses: actions/upload-artifact@master
        with:
          name: yarn-install-node-modules
          path: node_modules
  lint-format:
    runs-on: ubuntu-latest
    needs: lint-yarn-install
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Download Install Cache
        uses: actions/download-artifact@master
        with:
          name: yarn-install-node-modules
          path: node_modules
      - name: Yarn Install
        run: yarn install
      - name: Run Prettier
        run: 'yarn prettier:check'
  lint-js-ts:
    runs-on: ubuntu-latest
    needs: lint-yarn-install
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Download Install Cache
        uses: actions/download-artifact@master
        with:
          name: yarn-install-node-modules
          path: node_modules
      - name: Yarn Install
        run: yarn install
      - name: Lint
        run: yarn lint
  lint:
    runs-on: ubuntu-latest
    needs: [lint-generated, lint-markdown, lint-python, lint-format, lint-js-ts]
    steps:
      - name: All passing
        run: echo "All passing!"
