name: lint-python
on:
  push:
    paths:
      - '.github/workflows/lint-python.yml'
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install linters
        run: python3 -m pip install -U black flake8
      - name: Lint with black
        run: black --check .
      - name: Lint with flake8
        run: flake8 .
