name: lint-generated
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            .pnp.js
          key: yarn-berry-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-berry-
      - name: Yarn Install
        run: yarn install
      - name: Generate Workflows
        run: yarn workspace @dev-sam/repo-tools compile
      - name: Generate Workflows
        run: yarn codegen
      - name: Check changed
        run: |
          git status --porcelain
          if [[ `git status --porcelain` ]]; then
            echo "Generated files are not in sync!"
            exit 1
          else
            echo "Generated files are in sync. Good to go!"
          fi
