name: lint-js-ts
on:
  push:
    paths:
      - '.github/workflows/lint-js-ts.yml'
      - '**.js'
      - '**.ts'
      - '**.jsx'
      - '**.tsx'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - uses: actions/cache@preview
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Yarn Install
        run: yarn install
      - name: Run Prettier
        run: 'yarn format:check'
      - name: Run ESLint
        run: yarn lint
