name: lint-generated
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "::add-path::/home/runner/.deno/bin"
      - name: Generate Workflows
        run: ./tools/generate
      - name: Check changed
        run: |
          git status --porcelain
          if [[ `git status --porcelain` ]]; then
            echo "Generated files are not in sync!"
            exit 1
          else
            echo "Generated files are in sync. Good to go!"
          fi
