name: lint
on: push

jobs:
  lint-js-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install
      - name: Build sam-highlighter
        run: yarn workspace sam-highlighter build
      - name: Lint
        run: yarn lint
  lint-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install
      - name: Build tooling
        run: yarn workspace tooling build
      - name: Generate Workflows
        run: yarn generate-workflows --out .github/workflows
      - name: Check changed
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Workflow files are not in sync!"
            exit 1
          else
            echo "Workflow files are in sync. Good to go!"
          fi
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
      - name: Setup Markdown Lint
        run: gem install mdl
      - name: Run Markdown Lint
        run: mdl .
