name: lint
on: push

jobs:
  lint-js-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Yarn Install
        run: yarn install
      - name: Build sam-highlighter
        run: yarn workspace sam-highlighter build
      - name: Lint
        run: yarn lint
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
      - name: Setup Markdown Lint
        run: gem install mdl
      - name: Run Markdown Lint
        run: mdl .
